### ISSUE TITLE
review and Fix command permissions

### ISSUE THREAD

**Issue by dasbif** [JoshCode/gilmore#30]
known issues:

`!help <command>` command displays permissions incorrectly (displays none when some exist in some cases, for example)
`!game create` is Dexcuracy-only.  Should be available to Mods and Administrators.
`!custom list` is either Mod or Administrator-only.  Should be available to all users.

**Comment by JoshCode** [comment]
Issue has been split up in 3 issues, #31, #32, #33. An issue should always address one thing, not multiple.
