### ISSUE TITLE
!help <command> displays permissions incorrectly

### ISSUE THREAD

**Issue by JoshCode** [JoshCode/gilmore#31]
Original issue by @dasbif in #30

`!help <command>` command displays permissions incorrectly (displays none when some exist in some cases, for example)

**Comment by JoshCode** [comment]
@dasbif Could you be specific as to what permissions display incorrectly?

**Comment by dasbif** [comment]
@JoshCode `!help !game`, `!help !custom`, both show permissions: none, which is inaccurate for both of those commands.  Both have several sub-commands which should have different permission levels.
