### ISSUE TITLE
Starting Time Guessing Game

### ISSUE THREAD

**Issue by JoshCode** [JoshCode/gilmore#4]

**Comment by prscampbell** [comment]
This command will handle the Time Guessing Game that happens before Critical Role starts.

!timegame, with no parameters, will display the rules of the game.

An admin will begin this game by using a `!timegame start` command. This will print out the rules of the game, (similarly to the !timegame basic command) and begin listening for any `!timegame [TIME]` messages.

When a user does a !timegame, these will be stored in a Map<String, String> which will contain the key which is the unique ID of the user who enter the command, and the value they entered which is the time in Pacific Standard Time. They will be able override their current value, but only vote once. The format of the input will be HH:MM where the hour is NOT the 24 hour format, it is assumed that Critical Role will always be in the evening.

Voting will automatically stop at 6:59:59 PM PST via a task running in the background to check what the current time is (once every second to be as accurate as possible). Once voting as been ended, a message will be sent out by the bot to alert users of this.

An admin will end this game, when Critical Role starts, using the !timegame end command. This will take the current time (in PST) and find out who guessed the right time.

**Comment by dasbif** [comment]
We no longer do the guessing game, don't need to implement this feature anymore.
